[phases.setup]
nixPkgs = ["nodejs_20", "pnpm", "python3", "pkg-config", "cairo", "pango", "libjpeg", "giflib", "librsvg", "pixman"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm railway:start"